### PR TITLE
Fet: Buy greades limit(per a round)

### PR DESCRIPTION
**Pull request by jonathan-up**
The default behavior of the game only limits the maximum number of buying, you can still buy grenades again after you use them

### CODE REVIEW

**Comment by SmileYzn** [comment]
Why not set freezetime exactly to 15 seconds? When freezetime ends, buy time shoud end.

I always tryed to understand that fix

**Comment by jonathan-up** [comment]
Most people buy items outside the freezetime for a variety of reasons

**Comment by jonathan-up** [comment]
Just additional feature, it could be set 0 to disable it. “Harmless” hah.

**Comment by SmileYzn** [comment]
I will try to do that using rebuy struct instead of do manually checks in matchbot code

**Comment by SmileYzn** [comment]
I launch a action build with this idea. and variables too.
But i used m_rgItems of CBasePlayer to check the number of grenades per round.

```
// Number of HE grenade allowed per round
//
// 0 Disable restriction
//
// Default "0"
mb_round_grenade_count "0"

// Number of smoke grenade allowed per round
//
// 0 Disable restriction
//
// Default "0"
mb_round_smoke_count "0"

// Number of flashbangs allowed per round
//
// 0 Disable restriction
//
// Default "0"
mb_round_flash_count "0"
```

To be honest, i guess a simple check if player is buying more grenades out of freezetime will solve this issue to.

Like

```
	if (type == ITEM_TYPE_BUYING)
	{
		if (item == ITEM_HEGRENADE || item == ITEM_SMOKEGRENADE || item == ITEM_FLASHBANG)
		{
			if (gMatchBot.GetState() == STATE_FIRST_HALF || gMatchBot.GetState() == STATE_SECOND_HALF || gMatchBot.GetState() == STATE_OVERTIME)
			{
				if (g_pGameRules)
				{
					if (!CSGameRules()->IsFreezePeriod())
					{
						gMatchUtil.ClientPrint(Player->edict(), PRINT_CENTER, "#Cstrike_TitlesTXT_Weapon_Not_Available");

						return true;
					}
				}
			}
		}
	}
```

I really do not know what is the best solution, but yout idea is now part of matchbot

Really thanks for contribution! 🙇‍♂️ 🙏 👏

**Comment by jonathan-up** [comment]
This can result in careless players not being able to buy grenades outside of the freezetime

**Comment by SmileYzn** [comment]
Did you tested it? Any buy in freeze time will reset that and players will able to buy

**Comment by jonathan-up** [comment]
Not test yet. But I check your code
`
if (CSGameRules()->IsFreezePeriod() && !Player->m_rgAmmo[AMMO_HEGRENADE])
{
	// Reset variable
	Player->m_rgItems[0] = 0;
}
`
you reset `m_rgItems` on freezetime only, maybe this means that if a player forgets to buy grenades, he cannot buy it outside of the freeze time because `m_rgItems` not reset.

**Comment by jonathan-up** [comment]
Or the player has a flash bomb left over from the previous round, This may also cause the `m_rgItems` not to be reset

**Comment by SmileYzn** [comment]
I will put roundRestart event, since i try to put in this way to avoid more one hook to Round Restart

👍

**Comment by SmileYzn** [comment]
I guess that should work now!

Thanks for patience bro 🙏

**Comment by jonathan-up** [comment]
emm... I think it should not put reset data on `Round Restart`, it shoud on `Player Spawn`, and set data as player's bpammo. this fix if player have grenades from pre round,  he can still use them and buy them again.

**Comment by jonathan-up** [comment]
like this.
微信图片_20240131122045
微信图片_20240131122202

**Pull request closed without merging**
