### PR TITLE
Prefixes on admin and players

### PR DESCRIPTION
**Pull request by yuyiken**
Hi, I saw it was some issues with player .prefixesand admin !prefixes. 

I make this changes, and was working for me. But the problem is when you change it on cfg you need change it manually on users  and admin motd. 

Maybe if you have some better ideas I can work on it.

### CODE REVIEW

**Comment by SmileYzn** [comment]
Why remove . prefixes? To use with variables?

**Comment by yuyiken** [comment]
Yes, I thought m_AdminPrefix and m_PlayerPrefix, was made for that function to define prefixes for player and admin commands. 

If it wasnt, just close the pull.

**Comment by SmileYzn** [comment]
I will just create a json config for that commands and remove mb_admin_prefix and mb_player_prefix variables.

I really like the suggestion of code change and pull request itself, But do not make sense to change only command prefixes, instead of all of commands name.

**Comment by yuyiken** [comment]
Sure, I'll be glad to test new stuff as always.

**Pull request closed without merging**
